services:
  db:
    image: docker.io/library/postgres:13
    container_name: db
    environment:
      POSTGRES_USER: flaskuser
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: flaskdb
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    security_opt:
      - apparmor=unconfined

  app:
    build: ./app
    container_name: app
    image: localhost/myapp_app:latest
    ports:
      - "5000:5000"
    depends_on:
      db:
        condition: service_started
    environment:
      DB_HOST: db
      DB_USER: flaskuser
      DB_PASSWORD: secret
      DB_NAME: flaskdb
    security_opt:
      - apparmor=unconfined

volumes:
  db_data:
