# Этап сборки
FROM golang:1.21 AS builder
WORKDIR /app
COPY . .
RUN go mod init myapp && \
    go mod tidy && \
    CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -o myapp .

# Этап запуска
FROM alpine:latest
WORKDIR /root/
COPY --from=builder /app/myapp .
EXPOSE 8080
CMD ["./myapp"]
